
# This script checks the multiple MX records against 80 DNS Blacklist providers, write a log with date & time stamp for auditing purpose and sends email to specified email address
#>
# Feel free to add any missing DNBL 
$blacklistServers = @(
'srn.surgate.net'
'0spamtrust.fusionzero.com'
'query.bondedsender.org'
'plus.bondedsender.org'
'whitelist.sci.kun.nl'
'cml.anti-spam.org.cn'
'rwl.choon.net'
'list.dnswl.org'
'accredit.habeas.com'
'sa-accredit.habeas.com'
'hul.habeas.com'
'sohul.habeas.com'
'nobl.junkemailfilter.com'
'dnswl.inps.de'
'iadb.isipp.com'
'iadb2.isipp.com'
'wadb.isipp.com'
'wl.mailspike.net'
'trusted.nether.net'
'wl.nszones.com'
'ispmx.pofon.foobar.hu'
'whitelist.surriel.com'
'eswlrev.dnsbl.rediris.es'
'mtawlrev.dnsbl.rediris.es'
'swl.spamhaus.org'
'wbl.triumf.ca'
'ips.whitelisted.org'
'hostkarma.junkemailfilter.com'
'rep.mailspike.net'
'bl.spamstinks.com'
'badhost.stopspam.org'
'block.stopspam.org'
'dnsbl.stopspam.org'
'dul.pacifier.net'
'bl.suomispam.net'
'gl.suomispam.net'
'multi.surbl.org'
'dnsrbl.swinog.ch'
'st.technovision.dk'
'dnsbl.tornevall.org'
'rbl2.triumf.ca'
'truncate.gbudb.net'
'dnsbl-0.uceprotect.net'
'dnsbl-1.uceprotect.net'
'dnsbl-2.uceprotect.net'
'dnsbl-3.uceprotect.net'
'ubl.unsubscore.com'
'free.v4bl.org'
'ip.v4bl.org'
'virbl.dnsbl.bit.nl'
'dnsbl.webequipped.com'
'blacklist.woody.ch'
'db.wpbl.info'
'bl.blocklist.de'
'dnsbl.zapbl.net'
'vote.drbl.caravan.ru'
'work.drbl.caravan.ru'
'autowork.drbl.ks.cz'
'czdynamic.drbl.ks.cz'
'vote1.drbl.ks.cz'
'work.drbl.ks.cz'
'vote.drbldf.dsbl.ru'
'work.drbldf.dsbl.ru'
'vote.drbl.gremlin.ru'
'work.drbl.gremlin.ru'
'bl.drmx.org'
'dnsbl.dronebl.org'
'rbl.efnet.org'
'rbl.efnetrbl.org'
'tor.efnet.org'
'bl.emailbasura.org'
'rbl.fasthosts.co.uk'
'fnrbl.fast.net'
'forbidden.icm.edu.pl'
'hil.habeas.com'
'dnsbl.cobion.com'
'lookup.dnsbl.iip.lu'
'spamrbl.imp.ch'
'wormrbl.imp.ch'
'dnsbl.inps.de'
'rbl.interserver.net'
'rbl.iprange.net'
'mail-abuse.blacklist.jippg.org'
'dnsbl.justspam.org'
'dnsbl.kempt.net'
'spamlist.or.kr'
'bl.konstant.no'
'relays.bl.kundenserver.de'
'spamguard.leadmon.net'
'rbl.lugh.ch'
'dnsbl.madavi.de'
'bl.mailspike.net'
'z.mailspike.net'
'bl.mav.com.br'
'cidr.bl.mcafee.com'
'rbl.megarbl.net'
'combined.rbl.msrbl.net'
'images.rbl.msrbl.net'
'phishing.rbl.msrbl.net'
'spam.rbl.msrbl.net'
'virus.rbl.msrbl.net'
'web.rbl.msrbl.net'
'relays.nether.net'
'unsure.nether.net'
'ix.dnsbl.manitu.net'
'no-more-funn.moensted.dk'
'dyn.nszones.com'
'sbl.nszones.com'
'bl.nszones.com'
'dnsbl.openresolvers.org'
'spam.pedantic.org'
'pofon.foobar.hu'
'dnsbl.proxybl.org'
'psbl.surriel.com'
'all.rbl.jp'
'short.rbl.jp'
'virus.rbl.jp'
'rbl.rbldns.ru'
'rbl.schulte.org'
'rbl.talkactive.net'
'access.redhawk.org'
'dnsbl.rizon.net'
'dynip.rothen.com'
'dnsbl.rymsho.ru'
'all.s5h.net'
'bl.scientificspam.net'
'tor.dnsbl.sectoor.de'
'exitnodes.tor.dnsbl.sectoor.de'
'bl.score.senderscore.com'
'singular.ttk.pte.hu'
'dnsbl.sorbs.net'
'problems.dnsbl.sorbs.net'
'proxies.dnsbl.sorbs.net'
'relays.dnsbl.sorbs.net'
'safe.dnsbl.sorbs.net'
'dul.dnsbl.sorbs.net'
'zombie.dnsbl.sorbs.net'
'block.dnsbl.sorbs.net'
'escalations.dnsbl.sorbs.net'
'http.dnsbl.sorbs.net'
'misc.dnsbl.sorbs.net'
'smtp.dnsbl.sorbs.net'
'socks.dnsbl.sorbs.net'
'spam.dnsbl.sorbs.net'
'recent.spam.dnsbl.sorbs.net'
'new.spam.dnsbl.sorbs.net'
'old.spam.dnsbl.sorbs.net'
'web.dnsbl.sorbs.net'
'korea.services.net'
'backscatter.spameatingmonkey.net'
'badnets.spameatingmonkey.net'
'bl.spameatingmonkey.net'
'netbl.spameatingmonkey.net'
'singlebl.spamgrouper.com'
'netblockbl.spamgrouper.com'
'bl.spamcannibal.org'
'dnsbl.spam-champuru.livedoor.com'
'bl.spamcop.net'
'pbl.spamhaus.org'
'sbl.spamhaus.org'
'sbl-xbl.spamhaus.org'
'xbl.spamhaus.org'
'zen.spamhaus.org'
'feb.spamlab.com'
'rbl.spamlab.com'
'all.spamrats.com'
'dyna.spamrats.com'
'noptr.spamrats.com'
'spam.spamrats.com'
'spamsources.fabel.dk'
'aspews.ext.sorbs.net'
'dnsbl.aspnet.hu'
'ips.backscatterer.org'
'b.barracudacentral.org'
'bb.barracudacentral.org'
'list.bbfh.org'
'l1.bbfh.ext.sorbs.net'
'l2.bbfh.ext.sorbs.net'
'l3.bbfh.ext.sorbs.net'
'l4.bbfh.ext.sorbs.net'
'netscan.rbl.blockedservers.com'
'rbl.blockedservers.com'
'spam.rbl.blockedservers.com'
'list.blogspambl.com'
'bsb.empty.us'
'bsb.spamlookup.net'
'blacklist.sci.kun.nl'
'cbl.anti-spam.org.cn'
'cblplus.anti-spam.org.cn'
'cblless.anti-spam.org.cn'
'cdl.anti-spam.org.cn'
'cbl.abuseat.org'
'rbl.choon.net'
'bogons.cymru.com'
'v4.fullbogons.cymru.com'
'torexit.dan.me.uk'
'rbl.dns-servicios.com'
'dnsbl.net.ua'
'dnsbl.rv-soft.info'
'0spam.fusionzero.com'
'0spam-killlist.fusionzero.com'
'ipbl.zeustracker.abuse.ch'
'rbl.abuse.ro'
'spam.dnsbl.anonmails.de'
'dnsbl.anticaptcha.net'
'orvedb.aupads.org'
'rsbl.aupads.org'
)
# Array of IP addresses if you need to check against multiple MX records for your domain.
$IPlist = @(
'151.80.93.100' # ps-mx-1.flintstudios.net
'151.80.93.101' # ps-app-1.flintstudios.net
'5.135.37.42'
'46.105.214.37' #fs-ws-1.flintstudios.net
'176.31.131.171' #fs-whm-1.flintstudios.net
'5.135.37.44' #ps-ws-1.flintstudios.net

)
foreach ($IP in $IPList) {
# This function writes output to a log file "Check_Blacklist_Providers_IP"
#function log ($string) {
#(date -format "HH:mm:sstt, dd MMM yyyy | ") + $string | Out-file "C:\Scripts\Check_Blacklist_Providers_$IP.log" -a -en ASCII
#Write-Output $string
#}
$reversedIP = ($IP -split '\.')[3..0] -join '.'
$blacklistedOn = @()
foreach ($server in $blacklistServers) {
$fqdn = "$reversedIP.$server"
try
{
$null = [System.Net.Dns]::GetHostEntry($fqdn)
$blacklistedOn += $server
}
catch { }
}
if ($blacklistedOn.Count -gt 0) {
log (write-output "$IP blacklisted on the following servers: $($blacklistedOn -join ', ')")
# variable store value sent by the $blackliston
$finaltext = "$IP is blacklisted on the following servers: $($blacklistedOn -join ', ')"
# This one line which sent email of the output.
Send-MailMessage -To "domains@flintstudios.co.uk" -From "alerting@flintstudios.co.uk" -Subject "$IP detected on a DNS Blacklist" -Body $finaltext -SmtpServer "fs-ws-1.flintstudios.net" -BodyAsHtml
}
else {log (Write-Output "$IP is OK")}
}
